package surfacer

// help documents the metrics Argus emits; an absent name gets no HELP line.
var help = map[string]string{
	"probe_total":                       "Probe attempts.",
	"probe_success_total":               "Successful probe attempts.",
	"probe_failure_total":               "Failed probe attempts, by reason.",
	"probe_up":                          "Whether the last probe of this backend succeeded.",
	"probe_duration_seconds":            "Probe duration, excluding name resolution.",
	"probe_last_duration_seconds":       "Duration of the last probe.",
	"probe_phase_duration_seconds":      "Probe duration split into phases.",
	"probe_phase_last_duration_seconds": "Phase durations of the last probe.",
	"resolve_duration_seconds":          "Time spent resolving the target, cache hits excluded.",
	"resolve_last_duration_seconds":     "Time of the last real resolution.",
	"resolve_total":                     "Resolutions performed.",
	"resolve_failure_total":             "Failed resolutions.",
	"resolve_ttl_seconds":               "TTL of the DNS answer the backends came from.",
	"target_backends":                   "Addresses the target resolves to.",
	"target_backends_up":                "Addresses of the target that answered.",
	"target_backend_info":               "One series per address of the target.",
	"http_status_code":                  "HTTP status code of the last response.",
	"http_response_size_bytes":          "Bytes read from the response body, counted no further than twice max_body_bytes or the largest max_size_bytes.",
	"http_content_length":               "Content-Length of the response.",
	"http_redirects":                    "Redirects followed.",
	"http_connection_reused":            "Whether the connection was reused.",
	"http_validator":                    "Whether a validator passed, by name.",
	"tls_cert_expiry_days":              "Days until the leaf certificate expires.",
	"tls_chain_expiry_days":             "Days until the first certificate in the chain expires.",
	"tls_cert_valid":                    "Whether the certificate is valid right now.",
	"tls_cert_not_after_seconds":        "Leaf certificate expiry as a unix timestamp.",
	"tls_cert_not_before_seconds":       "Leaf certificate start as a unix timestamp.",
	"tls_chain_length":                  "Certificates presented by the server.",
	"tls_ocsp_stapled":                  "Whether the server stapled an OCSP response.",
	"tls_cert_fingerprint_info":         "SHA-256 of the leaf certificate, as a label.",
	"tls_cert_serial_info":              "Serial number of the leaf certificate, as a label.",
	"dns_queries_total":                 "DNS queries sent, by resolver.",
	"dns_query_failures_total":          "DNS queries that failed, by resolver.",
	"dns_answers":                       "Records in the answer.",
	"dns_ttl_seconds":                   "Smallest TTL in the answer.",
	"dns_consistent":                    "Whether every resolver returned the same answer set.",
	"dns_authority_rrs":                 "Records in the authority section.",
	"dns_additional_rrs":                "Records in the additional section.",
	"dns_authoritative":                 "Whether the resolver answered from the zone rather than a cache.",
	"dns_soa_serial":                    "SOA serial of the zone, the number a transfer is keyed on.",
	"icmp_packets_sent":                 "ICMP echo requests sent.",
	"icmp_packets_received":             "ICMP echo replies received.",
	"icmp_packet_loss_percent":          "Packet loss over the last run.",
	"icmp_rtt_avg_seconds":              "Mean round-trip time.",
	"icmp_rtt_min_seconds":              "Smallest round-trip time.",
	"icmp_rtt_max_seconds":              "Largest round-trip time.",
	"icmp_rtt_jitter_seconds":           "Mean deviation from the average round-trip time.",
	"icmp_reply_hop_limit":              "TTL the reply arrived with: hops on the return path.",
	"probe_success":                     "Whether the on-demand check of this target passed.",
	"domain_expiry_days":                "Days until the domain's registration expires.",
	"domain_expiry_seconds":             "Registration expiry as a unix timestamp.",
	"domain_registered_seconds":         "When the domain was first registered, as a unix timestamp.",
	"domain_age_days":                   "Days since the domain was first registered.",
	"domain_locked":                     "Whether the domain carries the registrar transfer lock.",
	"domain_registrar_info":             "The registrar holding the domain, as a label.",
	"domain_status_info":                "The registry status codes, as a label.",
	"domain_lookup_duration_seconds":    "Time the registry took to answer.",
	"discovery_failures":                "Failed discovery refreshes since the agent started.",
	"discovery_age_seconds":             "How long the served target list has been standing.",
	"resolve_fallback_total":            "Resolutions answered by the other address family.",
	"tcp_response_size_bytes":           "Bytes read during the TCP conversation.",
	"udp_response_size_bytes":           "Bytes of the UDP reply.",
	"probe_backends_down":               "Addresses of a probe that did not answer.",
	"probe_runs_paused":                 "Runs the schedule suppressed.",
	"probe_sleeping":                    "Whether the schedule has the probe paused right now.",
	"uptime_seconds":                    "Time since the agent started.",
	"goroutines":                        "Goroutines in the agent.",
	"memory_bytes":                      "Heap in use by the agent.",
	"probes_configured":                 "Probes currently running.",
	"probe_targets":                     "Targets of a probe.",
	"probe_runs_skipped":                "Runs skipped because the previous one was still going.",
	"probe_panics":                      "Probe calls that panicked.",
	"series":                            "Series held in the metric store.",
	"series_dropped":                    "Samples dropped after the series cap was reached.",
	"config_reloads":                    "Successful configuration reloads.",
	"config_reload_failures":            "Rejected configuration reloads.",
	"probe_slots_used":                  "Probe concurrency slots in use.",
	"probe_slots_total":                 "Probe concurrency slots available.",
	"build_info":                        "Agent version, as a label.",
}
