package surfacer

// help documents the metrics Argus emits; an absent name gets no HELP line.
var help = map[string]string{
	"probe_total":                       "Probe attempts.",
	"probe_success_total":               "Successful probe attempts.",
	"probe_failure_total":               "Failed probe attempts, by reason.",
	"probe_up":                          "Whether the last probe of this backend succeeded.",
	"probe_timeout_seconds":             "Deadline one request of this probe runs under.",
	"probe_duration_seconds":            "Probe duration, excluding name resolution.",
	"probe_last_duration_seconds":       "Duration of the last probe.",
	"probe_phase_duration_seconds":      "Probe duration split into phases.",
	"probe_phase_last_duration_seconds": "Phase durations of the last probe.",
	"resolve_duration_seconds":          "Time spent resolving the target, cache hits excluded.",
	"resolve_last_duration_seconds":     "Time of the last real resolution.",
	"resolve_total":                     "Resolutions performed.",
	"resolve_failure_total":             "Failed resolutions.",
	"resolve_ttl_seconds":               "TTL of the DNS answer the backends came from.",
	"target_backends":                   "Addresses the target resolves to.",
	"target_backends_up":                "Addresses of the target that answered.",
	"target_backend_info":               "One series per address of the target.",
	"http_status_code":                  "HTTP status code of the last response.",
	"http_response_size_bytes":          "Bytes read from the response body, counted no further than twice max_body_bytes or the largest max_size_bytes.",
	"http_content_length":               "Content-Length of the response.",
	"http_redirects":                    "Redirects followed.",
	"http_connection_reused":            "Whether the connection was reused.",
	"http_validator":                    "Whether a validator passed, by name.",
	"probe_expect_info":                 "The named capture groups of what a pattern matched, as labels.",
	"icmp_duplicates":                   "Replies that arrived for a packet already answered.",
	"tls_cert_expiry_days":              "Days until the leaf certificate expires.",
	"tls_chain_expiry_days":             "Days until the first certificate in the chain expires.",
	"tls_chain_not_after_seconds":       "Expiry of the first certificate in the chain to expire, as a unix timestamp.",
	"tls_cert_valid":                    "Whether the certificate is valid right now.",
	"tls_cert_not_after_seconds":        "Leaf certificate expiry as a unix timestamp.",
	"tls_cert_not_before_seconds":       "Leaf certificate start as a unix timestamp.",
	"tls_chain_length":                  "Certificates presented by the server.",
	"tls_ocsp_stapled":                  "Whether the server stapled an OCSP response.",
	"tls_ocsp_status_info":              "What the OCSP responder said: good, revoked, unknown or unavailable.",
	"tls_ocsp_next_update_seconds":      "When the OCSP answer stops being current, as a unix timestamp.",
	"tls_cert_revoked":                  "Whether the OCSP responder reports the certificate as revoked.",
	"tls_cert_fingerprint_info":         "SHA-256 of the leaf certificate, as a label.",
	"tls_cert_serial_info":              "Serial number of the leaf certificate, as a label.",
	"dns_queries_total":                 "DNS queries sent, by resolver.",
	"dns_query_failures_total":          "DNS queries that failed, by resolver.",
	"dns_answers":                       "Records in the answer.",
	"dns_ttl_seconds":                   "Smallest TTL in the answer.",
	"dns_consistent":                    "Whether every resolver returned the same answer set.",
	"dns_authority_rrs":                 "Records in the authority section.",
	"dns_additional_rrs":                "Records in the additional section.",
	"dns_authoritative":                 "Whether the resolver answered from the zone rather than a cache.",
	"dns_soa_serial":                    "SOA serial of the zone, the number a transfer is keyed on.",
	"icmp_packets_sent":                 "ICMP echo requests sent.",
	"icmp_packets_received":             "ICMP echo replies received.",
	"icmp_packet_loss_percent":          "Packet loss over the last run.",
	"icmp_rtt_avg_seconds":              "Mean round-trip time.",
	"icmp_rtt_min_seconds":              "Smallest round-trip time.",
	"icmp_rtt_max_seconds":              "Largest round-trip time.",
	"icmp_rtt_jitter_seconds":           "Mean deviation from the average round-trip time.",
	"icmp_reply_hop_limit":              "TTL the reply arrived with: hops on the return path.",
	"probe_success":                     "Whether the on-demand check of this target passed.",
	"domain_expiry_days":                "Days until the domain's registration expires.",
	"domain_expiry_seconds":             "Registration expiry as a unix timestamp.",
	"domain_registered_seconds":         "When the domain was first registered, as a unix timestamp.",
	"domain_age_days":                   "Days since the domain was first registered.",
	"domain_locked":                     "Whether the domain carries the registrar transfer lock.",
	"domain_registrar_info":             "The registrar holding the domain, as a label.",
	"domain_status_info":                "The registry status codes, as a label.",
	"domain_lookup_duration_seconds":    "Time the registry took to answer.",
	"argus_discovery_failures":          "Failed discovery refreshes since the agent started.",
	"argus_discovery_age_seconds":       "How long the served target list has been standing.",
	"resolve_fallback_total":            "Resolutions answered by the other address family.",
	"tcp_response_size_bytes":           "Bytes read during the TCP conversation.",
	"udp_response_size_bytes":           "Bytes of the UDP reply.",
	"unix_response_size_bytes":          "Bytes read over the unix socket.",
	"websocket_handshake_status_code":   "Status code of the upgrade request; 101 is the only success.",
	"websocket_subprotocol_info":        "The subprotocol the server chose, as a label.",
	"websocket_response_size_bytes":     "Bytes of the message the server sent back.",
	"argus_probe_backends_down":         "Addresses of a probe that did not answer.",
	"argus_probe_runs_paused":           "Runs the schedule suppressed.",
	"argus_probe_sleeping":              "Whether the schedule has the probe paused right now.",
	"argus_uptime_seconds":              "Time since the agent started.",
	"argus_goroutines":                  "Goroutines in the agent.",
	"argus_memory_bytes":                "Heap in use by the agent.",
	"argus_probes_configured":           "Probes currently running.",
	"argus_probe_targets":               "Targets of a probe.",
	"argus_probe_runs_skipped":          "Runs skipped because the previous one was still going.",
	"argus_probe_panics":                "Probe calls that panicked.",
	"argus_series":                      "Series held in the metric store.",
	"argus_series_dropped":              "Samples dropped after the series cap was reached.",
	"argus_config_reloads":              "Successful configuration reloads.",
	"argus_config_reload_failures":      "Rejected configuration reloads.",
	"argus_probe_slots_used":            "Probe concurrency slots in use.",
	"argus_probe_slots_total":           "Probe concurrency slots available.",
	"argus_build_info":                  "Agent version, as a label.",

	"http_proto_info":            "Protocol of the final response, as a label.",
	"http_ssl":                   "Whether the request was made over TLS.",
	"http_final_url_info":        "Where the redirect chain ended, as a label.",
	"http_last_modified_seconds": "Last-Modified of the response, as a unix timestamp.",
	"tls_enabled":                "Whether the connection used TLS.",
	"tls_version_info":           "The TLS version negotiated, as a label.",
	"tls_cipher_info":            "The cipher suite negotiated, as a label.",
	"tls_alpn_info":              "The protocol ALPN selected, as a label.",
	"tls_handshake_resumed":      "Whether the session was resumed rather than negotiated.",
	"tls_cert_issuer_info":       "Issuer of the leaf certificate, as a label.",
	"tls_cert_subject_info":      "Subject of the leaf certificate, as a label.",
	"tls_cert_san_count":         "Names the leaf certificate covers.",
	"dns_rcode_info":             "The response code, as a label.",
	"dns_answer_info":            "The answer set joined into one label.",
	"dns_resolvers_failed":       "Resolvers that did not answer.",
	"grpc_serving_status":        "The health service's verdict; 1 is SERVING.",
	"grpc_status_info":           "The gRPC status code, as a label.",
	"external_exit_code":         "Exit status of the command.",
	"external_metrics_parsed":    "Metric lines accepted from the command's output.",

	// blackbox_exporter's names, which /probe publishes alongside the node's
	// own. Documented under the meaning blackbox gives them.
	"probe_http_status_code":                     "Status code of the last response.",
	"probe_http_version":                         "HTTP version of the final response, as a number.",
	"probe_http_content_length":                  "Content-Length of the response.",
	"probe_http_redirects":                       "Redirects followed.",
	"probe_http_ssl":                             "Whether the final request was made over TLS.",
	"probe_http_last_modified_timestamp_seconds": "Last-Modified of the response, as a unix timestamp.",
	"probe_http_duration_seconds":                "Request duration, split by phase.",
	"probe_dns_duration_seconds":                 "Query duration, split by phase.",
	"probe_icmp_duration_seconds":                "Round trip, split by phase.",
	"probe_ssl_earliest_cert_expiry":             "Expiry of the first certificate in the chain to expire, as a unix timestamp.",
	"probe_dns_lookup_time_seconds":              "Time spent resolving the target.",
	"probe_dns_answer_rrs":                       "Records in the answer section.",
	"probe_dns_authority_rrs":                    "Records in the authority section.",
	"probe_dns_additional_rrs":                   "Records in the additional section.",
	"probe_icmp_reply_hop_limit":                 "Hop limit the reply arrived with.",
	"probe_ip_protocol":                          "Address family the target was reached over: 4 or 6.",
	"probe_tls_version_info":                     "The TLS version negotiated, as a label.",
	"probe_failed_due_to_regex":                  "Whether a pattern is what failed the check.",
}
